[package]
name = "bsp"
version = "0.1.1"
authors = ["Vurich <jackefransham@gmail.com>"]
edition = "2018"

homepage = "https://github.com/Vurich/bsp"
repository = "https://github.com/Vurich/bsp"
description = "Crate to load BSP files efficiently - currently only works for Quake 3 BSP files. Fork of `quake3_loader` crate."
license = "MIT"

[dependencies]
arrayvec = "0.4"
bitflags = "1.0"
bv = "0.11"
byteorder = "0.5"

[features]
bench = []
