[package]
name = "bsp"
version = "0.2.0"
authors = ["Vurich <jackefransham@gmail.com>"]
edition = "2018"

homepage = "https://github.com/Vurich/bsp"
repository = "https://github.com/Vurich/bsp"
description = "Crate to load BSP files efficiently - currently only works for Quake 3 BSP files. Fork of `quake3_loader` crate."
license = "MIT"

[dependencies]
byteorder = "0.5"
arrayvec = "0.4"
