[package]
name = "vbsp"
version = "0.1.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
homepage = "https://github.com/icewind1991/vbsp"
repository = "https://github.com/icewind1991/vbsp"
description = "Rust parser for valve bsp files."
license = "MIT"
edition = "2018"
readme = "README.md"

[dependencies]
arrayvec = "0.5"
bitflags = "1.0"
bv = "0.11"
itertools = "0.10"
thiserror = "1.0"
lzma-rs = "0.1"
binread = "1.0"
parse-display = "0.4"
static_assertions = "1.1"

[dev-dependencies]
obj = "0.10"
main_error = "0.1.0"

[features]
bench = []
