[package]
name = "vbsp"
version = "0.1.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
homepage = "https://github.com/icewind1991/vbsp"
repository = "https://github.com/icewind1991/vbsp"
description = "Rust parser for valve bsp files."
license = "MIT"
edition = "2021"
readme = "README.md"

[dependencies]
arrayvec = "0.7.2"
bitflags = "1.0"
bv = "0.11.1"
thiserror = "1.0.30"
lzma-rs = "0.2.0"
binrw = "0.8.0"
static_assertions = "1.1.0"
miette = "3.2.0"

[dev-dependencies]
obj = "0.10"
main_error = "0.1.0"
miette = { version = "3.2.0", features = ["fancy"] }

[features]
bench = []
